apiVersion: v1
kind: Service
metadata:
  name: dangjik-svc
spec:
  type: NodePort
  selector:
    app: dangjik        # server-a, server-b 둘 다 이 라벨을 갖고 있어서 하나의 Service가 두 Pod로 트래픽을 분산
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080    # http://<아무 Worker Public IP>:30080 으로 접속
